name: Sync with template

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Template Sync
        uses: BernhardStrauss/actions-template-sync@v0.8.0
        with:
          source_repo: "https://github.com/Az-FIRST/Az-RBSI.git"
          source_branch: "docs-beta-1"
          github_token: ${{ secrets.GITHUB_TOKEN }}
